Issue  #3 BasicHomePage Take1
malikhollins/GiftingApp pull request #8
Opened 2024-11-09 04:52 UTC by KKForever

Did a LOT in Home.razor. I think TemplatedBar was just shit I was working on, so you can delete it if you think its dumb. Uh, I couldn't figure out how to rename/delete pages! So If I could maybe be explained that because well, you'll see.

DOWN TO HOME CONTENT>>>

Div CreateHouse is the entire "Add A New Home" Button Class.

The JoinButton will eventually also have a Div JoinHouse but im all about placeholders so no.

The Code Section, I think I might have code that I don't need, but I for the life of me can not figure out where anymore. I'm down for new ideas on whaat to call things! I definitely got myself a little confused...

Alsoo, the "Click to Create a GiftHouse Button" is also a placeholder. It does nothing  atm. The gameplan is for it to open up into the "createHouse"div

This is barebones, to be continued after its checked out.

2024-11-09 14:52 UTC, malikhollins commented on ClientApp/ClientApp.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ClientApp", "ClientApp\ClientApp.csproj", "{9AAC6247-A06C-4281-8F7A-2D598C51C6FB}"
Is this why you couldn't open the project?

2024-11-09 15:03 UTC, malikhollins requested changes

2024-11-09 15:03 UTC, malikhollins commented on ClientApp/ClientApp/Components/Pages/Home.razor
> +<button>Click to Create a GiftHouse!</button>
You have two buttons to create a Gift house. I think one will do.

2024-11-09 15:03 UTC, malikhollins commented on ClientApp/ClientApp/Components/Pages/Home.razor
> +<div class="createHouse" style="border:1px solid black;">
Preferred you move the styling into its own file e.g. `Home.razor.css`

2024-11-09 15:03 UTC, malikhollins commented on ClientApp/ClientApp.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ClientApp", "ClientApp\ClientApp.csproj", "{9AAC6247-A06C-4281-8F7A-2D598C51C6FB}"
I'll do some investigation here

2024-11-09 15:10 UTC, malikhollins commented on ClientApp/ClientApp.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ClientApp", "ClientApp\ClientApp.csproj", "{9AAC6247-A06C-4281-8F7A-2D598C51C6FB}"
Seems fine. Did you copy and paste this or did this occur automatically?

2024-11-09 15:59 UTC, KKForever commented on ClientApp/ClientApp.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ClientApp", "ClientApp\ClientApp.csproj", "{9AAC6247-A06C-4281-8F7A-2D598C51C6FB}"
automatically, idk what that even means or is

2024-11-09 16:00 UTC, KKForever commented on ClientApp/ClientApp/Components/Pages/Home.razor
> +<button>Click to Create a GiftHouse!</button>
can you... duplicate buttons with code?

2024-11-09 16:07 UTC, KKForever commented
![EditedHome1](https://github.com/user-attachments/assets/0fdd3cf8-af57-4244-9102-1dbc2f510c36)
![EditedHome1 1](https://github.com/user-attachments/assets/dc1ce685-2fdc-4bc0-84ae-3710df2f4c28)
![EditedHome1 2](https://github.com/user-attachments/assets/0037c7e4-e973-49c9-99cd-03e0934db6f5)
![EditedHome1 3](https://github.com/user-attachments/assets/68e0a3a4-3963-43dc-ad9e-a2ee9eacdf6e)

Okay so my issue is that I really don't understand Blazor! So if you could maybe find something that shows how to make a css page AND connect it to the right page, and send it, ill be down but its so frustrating finding blazor documentation that makes sense to me(im sorry but i need it a lil dumbed down)(with code examples that also make sense directly). Orrrrr, you could make the page, toss it back to me, and ill plug everything else in. That's the same with Models! The video you showed me had to do with server, and idk where the files go or how to actually use them in the home page from their respective pages. Im deadass just using c# documentation atm and its getting me far but not blazor far im so sorry.

2024-11-09 16:08 UTC, KKForever commented on ClientApp/ClientApp/Components/Layout/TemplatedBar.razor
> +}
Ngl that was my plan, but I realized I was getting sidetracked at that point and the issue was "BASIC HOME PAGE" and when i actually read what you wrote I realized I was doing too much for the moment.

2024-11-09 16:10 UTC, KKForever commented on ClientApp/ClientApp/Components/Pages/Home.razor
> +<header>
yes! Realize we probably only need one h-element in our navigation though. But for visuals, I added it.

2024-11-09 16:11 UTC, KKForever commented on ClientApp/ClientApp.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ClientApp", "ClientApp\ClientApp.csproj", "{9AAC6247-A06C-4281-8F7A-2D598C51C6FB}"
oh, I was at one point having issues pulling up how to open the application. I was trying a lot of things, and it might just be one of my failed attempts at figuring it out.

2024-11-10 13:48 UTC, malikhollins commented on ClientApp/ClientApp/Components/Pages/Home.razor
> +<button>Click to Create a GiftHouse!</button>
Never mind, I see the buttons have two separate goals.

2024-11-10 13:49 UTC, malikhollins commented on ClientApp/ClientApp/Components/Pages/Home.razor
> +<header>
Let's remove it for now. I'll put that into its own ticket.

2024-11-10 13:51 UTC, malikhollins commented on ClientApp/ClientApp/Components/Layout/TemplatedBar.razor
> +}
Well you can still use this component for the basic home page. The user being able to have rows of home was a part of that.

2024-11-10 13:52 UTC, malikhollins commented on ClientApp/ClientApp/Components/Layout/TemplatedBar.razor
> +}
You can make a flag at the top of the page that could switch between two different types of users. But for this PR this will be good.

2024-12-07 17:24 UTC, malikhollins approved these changes

2024-12-07 21:56 UTC, merged